env:
  browser: true
  es6: true
extends: standard
globals:
  jQuery: true
  module: true
  exports: true
  require: true
parserOptions:
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  prefer-const: off
  no-var: off
  object-curly-spacing: off
